name: Deploy to ECR

on:
  push:
    branches:
      - dev/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "ap-northeast-1"
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::303282268504:role/GithubAssumeRoleWithWebIdentity"
  AWS_ECR_BO_IMAGE_NAME: "expo2025-backoffice"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.AWS_ECR_BO_IMAGE_NAME }}
        run: |
          docker build -f backoffice/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ vars.ENV_TAG }} .
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
